[platformio]
boards_dir = boards

[env:seeed_xiao_nrf52840_sense]
platform = nordicnrf52
board = seeed_xiao_nrf52840_sense
framework = arduino
monitor_speed = 115200
extra_scripts = pre:scripts/seeed_nrf52.py

platform_packages =
  framework-arduinoadafruitnrf52@https://files.seeedstudio.com/arduino/core/nRF52/Seeed_nRF52_Boards-1.1.13.tar.bz2

lib_deps =
  https://github.com/Seeed-Studio/Seeed_Arduino_LSM6DS3.git
